import {createAction} from 'util'

export const POST_CHANGELLY_CURRENCIES = createAction('POST_CHANGELLY_CURRENCIES');
export const POST_CHANGELLY_MINIMUM_AMOUNT = createAction('POST_CHANGELLY_MINIMUM_AMOUNT');
export const POST_CHANGELLY_EXCHANGE_AMOUNT = createAction('POST_CHANGELLY_EXCHANGE_AMOUNT');
export const POST_CHANGELLY_CREATE_TRANSACTION = createAction('POST_CHANGELLY_CREATE_TRANSACTION');
export const POST_CHANGELLY_TRANSACTIONS = createAction('POST_CHANGELLY_TRANSACTIONS');
export const POST_CHANGELLY_STATUS = createAction('POST_CHANGELLY_STATUS');
export const SET_FROM_TOKEN_LOGO = createAction('SET_FROM_TOKEN_LOGO');
export const SET_TO_TOKEN_LOGO = createAction('SET_TO_TOKEN_LOGO');
export const SET_TOKEN_ONE_TEXT_VALUE = createAction('SET_TOKEN_ONE_TEXT_VALUE');
export const SET_TOKEN_TWO_TEXT_VALUE = createAction('SET_TOKEN_TWO_TEXT_VALUE');
export const SET_TOKEN_FROM_AMOUNT = createAction('SET_TOKEN_FROM_AMOUNT');
export const POST_CHANGELLY_CREATE_ADDRESS_PAIR = createAction('POST_CHANGELLY_CREATE_ADDRESS_PAIR');