# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qcx' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for qcx
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'
  pod 'Google-Mobile-Ads-SDK'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  'DevSupport',
  'tvOS'
  # Add any other subspecs you want to use in your project
]

  pod 'CodePush', :path => '../node_modules/react-native-code-push'


  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'


  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  target 'qcxTests' do
    inherit! :search_paths
    # Pods for testing
  end


end

target 'qcx-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for qcx-tvOS

  target 'qcx-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == 'yoga'
          target.build_configurations.each do |config|
              config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
              config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
          end
      end
  end
end
