# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quadrigacx' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for quadrigacx
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  'DevSupport'
  # Add any other subspecs you want to use in your project
]

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'quadrigacxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'quadrigacx-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for quadrigacx-tvOS

  target 'quadrigacx-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
