# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quadriga' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for quadriga
  pod 'Firebase/Core'
  pod 'Firebase/Performance'
  pod 'Firebase/Crash'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  'DevSupport'
  # Add any other subspecs you want to use in your project
]

  target 'quadriga-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'quadrigaTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
